### PR TITLE
created light and dark colour palettes

### PR DESCRIPTION
**Pull request by aquivere**

### CODE REVIEW

**Review by aimenhamed — CHANGES_REQUESTED** [review]
we should just have a single palette, with colours like : "lightBlue" etc

**Comment by aquivere** [comment]
> we should just have a single palette, with colours like : "lightBlue" etc

hmm ok i see, how would u recommend to name the colours to differentiate between light theme and dark theme? @aimenhamed

**Comment by aimenhamed** [comment]
> > we should just have a single palette, with colours like : "lightBlue" etc
> 
> 
> 
> hmm ok i see, how would u recommend to name the colours to differentiate between light theme and dark theme in that case? @aimenhamed 

ah i see what u mean, can't we just prefix them according to the theme ?

**Comment by aquivere** [comment]
> > > we should just have a single palette, with colours like : "lightBlue" etc
> > 
> > 
> > hmm ok i see, how would u recommend to name the colours to differentiate between light theme and dark theme in that case? @aimenhamed
> 
> ah i see what u mean, can't we just prefix them according to the theme ?

tru ok i'll go with that then

**Review by aimenhamed — APPROVED** [review]

**Comment by aimenhamed** [comment]
i think all good for now. but we will come back to how we will look at dark mode and what we’re gonna do.

**Pull request merged**
