### PR TITLE
feat(backend): add offset query in GET courses request [ELEC-464]

### PR DESCRIPTION
**Pull request by vinsentcs**
Offset query in the /courses GET request returns 25 courses from the offset.

### CODE REVIEW

**Review by aimenhamed — CHANGES_REQUESTED** [review]
this _works_ however it doesnt solve our problem. we dont want our db query to get _all_ the courses, because this is what makes this api call expensive and take a lot of time. 

what u should do is make a custom db query that returns the courses with the offset, and also the query can sort this for you, instead of doing it  afterwards. hope this makes sense :)

**Comment by vinsentcs** [comment]
important change is in course.repository.ts. the query is almost the same as the previous one that gets all courses, but lines 95-98 are new.

**Review by aimenhamed — COMMENTED** [review]
looks good :) good job. did u test this ?

**Comment by vinsentcs** [comment]
i tested it manually by sending in a bunch of get requests including the edge cases. are there further tests i should do?

when you get to the last offset in the courses (offset=3078), a http error is thrown because the database returns 0 courses. should this be an intended feature?

**Review by aimenhamed — APPROVED** [review]

**Pull request merged**
